name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pest:
    name: Tests (Pest) L${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        laravel: [ 8, 9 ]
        php: [ 8.1 ]
        stability: [prefer-lowest, prefer-stable]

    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: composer require "illuminate/support:^${{ matrix.laravel }}.0"
      - name: Run tests
        run: vendor/bin/pest